version: '3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_USER: template
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: todo
      MYSQL_RANDOM_ROOT_PASSWORD: true
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  app:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - db
    